[package]
name = "nodejs-resolver"
version = "0.0.25"
edition = "2021"
license = "MIT"
description = "nodejs resolve"
repository = "https://github.com/bvanjoi/nodejs_resolver"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { version = "1.0.81", features = ["preserve_order"] }
indexmap = "1.9.1"
dashmap = "5.3.4"
daachorse = "0.4.3"
once_cell = "1.12.0"
phf = { version = "0.10.1", features = ["macros"] }
smol_str = "0.1.23"
tracing = "0.1.35"
jsonc-parser = { version = "0.19.0", features = ["serde"] }

[dev-dependencies]
tracing-subscriber = "0.3.11"
tracing-span-tree = "0.1.1"

[profile.bench]
lto = true

[profile.release]
lto = true