name: bench

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/*.md"
      - LICENSE
      - "**/*.gitignore"
      - .editorconfig
  pull_request: null

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        manager: [npm, pnpm]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Install minimal nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: bench/package-lock.json
      - name: Configure Rust cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: bench-${{ runner.os }}-cargo-gcc-${{ matrix.gcc }}-clang-${{ matrix.clang }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Generate bench case and run
        run: |
          cd ./bench
          bash ./scripts/run.sh ${{ matrix.manager }}
          cd ..
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "cargo"
          output-file-path: ./bench/rs_bench.txt
          external-data-json-path: ./cache/benchmark-data.json
          comment-always: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
